version: '3'
services:
  web:
    image: joshyang/comp3916_assignment_restful_api
    volumes:
      - app-data:/code
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    restart: always
  redis:
    image: "redis:alpine"
    networks:
      - backend

volumes:
  app-data:

networks:
  frontend:
  backend:
